version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.41.0
    volumes:
      - ./backend/monitorization/prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9092:9092"
    depends_on:
      - backend
  grafana:
    image: grafana/grafana:9.3.2
    volumes:
      - ./backend/monitorization/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  backend:
    build: backend/gateway/main-server
    env_file:
      - backend/gateway/main-server/secrets/.env.development
    environment:
      - GIN_MODE=release
      - ENV_MODE=DOCKER
    volumes:
      - ./backend/gateway/main-server:/gin-server
    command: go run ./src/internal/cmd/main.go
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - "5081:80"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mongo:
    build: backend/gateway/database/mongodb
    ports:
        - '27018:27017'
    volumes:
        - ./backend/gateway/database/mongodb/mongodata:/data/db
    restart: always
    user: "1007:1007"
    # env_file:
    #   - mongodb/secrets/.env
    
volumes:
  grafana-data:
  prometheus-data: