version: "3.9"

services:

  images-server:
    build: images-server
    volumes:
      - ./images-server:/app
      - /app/node_modules
    stdin_open: true
    env_file:
      - images-server/.env
  backend:
    build: backend
    env_file:
      - backend/secrets/.env.production
    environment:
      - GIN_MODE=release
      - ENV_MODE=DOCKER
    volumes:
      - ./backend:/gin-server
    command: go run ./src/internal/cmd/main.go
    depends_on:
      - redis
      - mongo
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend-landing-page/build:/usr/share/nginx/html/lp
      - ./digital-twin-panel/build:/usr/share/nginx/html/dtp
  mongo:
    build: ./mongodb
    container_name: mongo
    ports:
        - '27018:27017'
    volumes:
        - ./mongodb/mongodata:/data/db
    restart: always
    # environment:
    #   MONGODB_ROOT_USER: "${MONGODB_ROOT_USER}"
    #   MONGODB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
    #   MONGODB_USER: "${MONGODB_USER}"
    #   MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
    #   MONGODB_DATABASE: "${MONGODB_DATABASE}"
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - ./redis/redisdata:/data
    command: redis-server
