version: "3.8"

services:

  frontend-landing-page:
    container_name: landing-page
    build: frontend-landing-page
    volumes:
      - ./frontend-landing-page:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    env_file:
      - frontend-landing-page/secrets/.env.local
      # The Go App
  backend:
    build: backend
    container_name: gin-server
    env_file:
      - backend/secrets/.env.local
    environment:
      - ENV_MODE=DOCKER
    ports:
        - "8080:8080"
    volumes:
        - ./backend:/gin-server
    command: go run ./src/internal/cmd/main.go
    restart: always
    depends_on:
        - 'mongo'
  mongo:
      image: 'mongo'
      container_name: mongo
      ports:
          - '27018:27017'
      volumes:
          - ./mongodata:/data/db
      restart: always
  # Mongo Express Web-based MongoDB admin interface
  mongo_express:
      image: mongo-express
      container_name: mongo_express
      depends_on:
          - 'mongo'
      ports:
          - '8081:8081'
      restart: always
      