version: '3.8'

services:

  frontend-landing-page:
    container_name: landing-page
    build: frontend-landing-page
    volumes:
      - ./frontend-landing-page:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    env_file:
      - frontend-landing-page/.env.production
    depends_on:
      - digital-twin-panel
  images-server:
    container_name: images-server
    build: images-server
    volumes:
      - ./images-server:/app
      - /app/node_modules
    ports:
      - "3500:3500"
    stdin_open: true
    env_file:
      - images-server/.env
  digital-twin-panel:
    container_name: digital-twin-panel
    build: digital-twin-panel
    volumes:
      - ./digital-twin-panel:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    stdin_open: true
    env_file:
      - digital-twin-panel/secrets/.env.development
    depends_on:
      - images-server
      - backend
  backend:
    build: backend
    container_name: gin-server
    env_file:
      - backend/secrets/.env.production
    environment:
      - GIN_MODE=release
      - ENV_MODE=DOCKER
    ports:
        - "8080:8080"
    volumes:
        - ./backend:/gin-server
    command: go run ./src/internal/cmd/main.go
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - ./backend:/redis
    command: redis-server
