version: "3.8"

services:

  images-server:
    build: images-server
    volumes:
      - images-server-data:/app/data
    stdin_open: true
    env_file:
      - images-server/secrets/.env.development
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./backend/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - backend
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./backend/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    
  backend:
    build: backend
    env_file:
      - backend/secrets/.env.development
    environment:
      - GIN_MODE=release
      - ENV_MODE=DOCKER
    volumes:
      - ./backend:/gin-server
    command: go run ./src/internal/cmd/main.go
    depends_on:
      - redis
      - mongo
  frontend:
    build: frontend
    restart: always
    ports:
      - "5081:80"
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot:ro
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt:rw
  #     - ./data/certbot/www:/var/www/certbot:rw
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mongo:
    build: ./mongodb
    container_name: mongo
    ports:
        - '27018:27017'
    volumes:
        - ./mongodb/mongodata:/data/db
    restart: always
    env_file:
      - mongodb/secrets/.env
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
        - "6379:6379"
    volumes:
        - ./redis/redisdata:/data
    command: redis-server
    
volumes:
  grafana-data:
  images-server-data: