version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./backend/monitorization/prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - backend
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./backend/monitorization/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
          - 5672:5672
          - 15672:15672
  backend:
    build: backend/gateway/main-server
    container_name: main-server
    env_file:
      - backend/gateway/main-server/secrets/.env.test
    environment:
      - ENV_MODE=DOCKER
    ports:
        - "8080:8080"
    volumes:
        - ./backend/gateway/main-server:/main-server
    command: go run ./src/internal/cmd/main.go
    restart: always
    depends_on:
        - 'mongo'
        - 'rabbitmq'
  mongo:
      build: backend/gateway/database/mongodb
      ports:
          - '27018:27017'
      volumes:
          - ./backend/gateway/database/mongodb/mongodata:/data/db
      restart: always
      # env_file:
      # - mongodb/secrets/.env
  frontend:
    build: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    stdin_open: true

volumes:
  grafana-data:
  prometheus-data: