const API_URL = process.env.REACT_APP_API_URL;
const NEWS_UPLOAD_URL = process.env.REACT_APP_NEWS_UPLOAD_URL;
const KEY_DECRYPT_PASSWD = process.env.REACT_APP_KEY_DECRYPT_PASSWD;
const IV_BLOCK_PASSWD = process.env.REACT_APP_IV_BLOCK_PASSWD;
const DIGITAL_TWIN_PANEL_URL =
  process.env.REACT_APP_DIGITAL_TWIN_PANEL_URL || "http://localhost:5173";
const EMAIL_SENDER_PUB_KEY = process.env.REACT_APP_EMAIL_SENDER_PUBKEY;
const EMAIL_SENDER_SERVICEID = process.env.REACT_APP_EMAIL_SENDER_SERVICEID;
const EMAIL_SENDER_TEMPLATEID = process.env.REACT_APP_EMAIL_SENDER_TEMPLATEID;
const ENV_MODE = process.env.NODE_ENV;
const IS_LOCAL = ENV_MODE === "development";

export {
  API_URL,
  NEWS_UPLOAD_URL,
  KEY_DECRYPT_PASSWD,
  IV_BLOCK_PASSWD,
  DIGITAL_TWIN_PANEL_URL,
  EMAIL_SENDER_PUB_KEY,
  EMAIL_SENDER_SERVICEID,
  EMAIL_SENDER_TEMPLATEID,
  IS_LOCAL,
};
