{
 "title": "Gin Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "gin_request_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gin_request_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "UV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gin_request_uv_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(gin_request_total[5m])", "legendFormat": "Traffic in" },
    { "expr": "rate(gin_request_uv_total[5m])", "legendFormat": "Traffic out" }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gin_uri_request_total{code=\"200\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Method",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gin_uri_request_total{code=\"200\"}",
     "legendFormat": "{{instance}}{{uri}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "gin_request_duration_count", "legendFormat": "{{uri}}" }
   ]
  },
  {
   "title": "Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(code, instance) (gin_uri_request_total)",
     "legendFormat": "{{instance}}-{{code}}"
    }
   ]
  },
  {
   "title": "Slow Request(default 5s)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}