global:
  scrape_interval: 120s
  evaluation_interval: 120s
  external_labels:
    monitor: "my_app"

rule_files:

scrape_configs:
  - job_name: myapp
    scrape_interval: 10s
    static_configs:
      - targets:
          - backend:8080
