global:
  scrape_interval: 120s
  evaluation_interval: 120s
  external_labels:
    monitor: "my_app"

rule_files:

scrape_configs:
  - job_name: myapp
    scrape_interval: 30s
    static_configs:
      - targets:
          - gin-gonic:9093
  # - job_name: prometheus
  #   static_configs:
  #     - targets:
  #         - cadvisor:8081
