const API_URL = process.env.REACT_APP_API_URL;
const NEWS_UPLOAD_URL = process.env.REACT_APP_NEWS_UPLOAD_URL;
const KEY_DECRYPT_PASSWD = process.env.REACT_APP_KEY_DECRYPT_PASSWD;
const IV_BLOCK_PASSWD = process.env.REACT_APP_IV_BLOCK_PASSWD;
const PANEL_URI = process.env.REACT_APP_PANEL_URI;

export {
  API_URL,
  NEWS_UPLOAD_URL,
  KEY_DECRYPT_PASSWD,
  IV_BLOCK_PASSWD,
  PANEL_URI,
};
