const TOGGLE_NOTIFICATIONS = "TOGGLE_NOTIFICATIONS";
const TOGGLE_WEATHER = "TOGGLE_WEATHER";
const LOGOUT = "LOGOUT";
const LOGIN = "LOGIN";
const REFRESH_LOGIN = "REFRESH_LOGIN";

export { TOGGLE_NOTIFICATIONS, TOGGLE_WEATHER, LOGIN, LOGOUT, REFRESH_LOGIN };
