const TOGGLE_NOTIFICATIONS = "TOGGLE_NOTIFICATIONS";
const TOGGLE_WEATHER = "TOGGLE_WEATHER";
const LOGOUT = "LOGOUT";
const LOGIN = "LOGIN";
const REFRESH_LOGIN = "REFRESH_LOGIN";
const SET_PARCELS = "SET_PARCELS";
const SET_PARCELS_COMMONS = "SET_PARCEL_COMMONS";

export {
  TOGGLE_NOTIFICATIONS,
  TOGGLE_WEATHER,
  LOGIN,
  LOGOUT,
  REFRESH_LOGIN,
  SET_PARCELS,
  SET_PARCELS_COMMONS,
};
