---
title: 'GEDEFEC: Global analysis of sources'
author: "Autor: Jorge Laguna"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)
if (!require("corrplot")) install.packages("corrplot")
library(corrplot)
if (!require("psych")) install.packages("psych")
library(psych)
if (!require("cluster")) install.packages("cluster")
library("cluster")
if (!require("arules")) install.packages("arules")
library("arules")
if (!require("vcd")) install.packages(c("vcd", "vcdExtra"))
library("vcd")
if (!require("aws.s3")) install.packages("aws.s3")
library("aws.s3")
```
  
# Exploratory Data Analysis

...




