version: '3.8'
services:
  krakend:
    # "watch" is for hot reload
    build:
      context: .
      target: local
    ports:
      - 1234:1234
      - 8089:8089
      - 8090:8090
    environment:
      - API_KEY_DT=${API_KEY_DT}
    command: run -c /etc/krakend/krakend.json -d -p 8089

    