version: '3.8'
services:
  krakend:
    # "watch" is for hot reload
    build:
      context: .
      target: local
    ports:
      - 1234:1234
      - 8089:8089
      - 8090:8090
    environment:
      - API_KEY_DT=${API_KEY_DT}
      - STRIPE_KEY=${STRIPE_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    volumes:
      - ./stores:/etc/krakend/stores
      - ./krakend.json:/etc/krakend/krakend.json
    command: run -c /etc/krakend/krakend.json -d -p 8089
  stripe-cli:
    image: stripe/stripe-cli:latest
    entrypoint:
      - /bin/sh
      - -c
      - stripe login --api-key ${STRIPE_KEY} && stripe listen --forward-to http://krakend:8089/payment/webhook
    